# Generated by Django 3.0.7 on 2020-09-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200818_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='reference_number',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='workbook',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
