# Generated by Django 3.0.7 on 2020-09-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200902_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date Created'),
        ),
        migrations.AlterField(
            model_name='interestbearingaccount',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date Created'),
        ),
    ]
