# Generated by Django 3.0.7 on 2020-09-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200902_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date Created'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='interestbearingaccount',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date Created'),
        ),
        migrations.AlterField(
            model_name='interestbearingaccount',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
