# Generated by Django 3.0.7 on 2020-09-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200903_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='interestbearingaccount',
            name='created_date',
        ),
        migrations.AddField(
            model_name='account',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date updated'),
        ),
        migrations.AddField(
            model_name='interestbearingaccount',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date updated'),
        ),
    ]
