export const ADD_ACCOUNTING_ADJUSTMENT = 'ADD_ACCOUNTING_ADJUSTMENT';
export const GET_ACCOUNTING_ADJUSTMENTS = 'GET_ACCOUNTING_ADJUSTMENTS';
export const DELETE_ACCOUNTING_ADJUSTMENT = 'DELETE_ACCOUNTING_ADJUSTMENT';
export const GET_ACCOUNTING_ADJUSTMENT = 'GET_ACCOUNTING_ADJUSTMENT'
