export const ADD_ACCOUNTING_POST = 'ADD_ACCOUNTING_POST';
export const GET_ACCOUNTING_POSTS = 'GET_ACCOUNTING_POSTS';
export const DELETE_ACCOUNTING_POST = 'DELETE_ACCOUNTING_POST';
export const GET_ACCOUNTING_POST = 'GET_ACCOUNTING_POST'
