export const GET_ACTIVE_CUSTOMERS = 'GET_ACTIVE_CUSTOMERS';
export const ADD_ACTIVE_CUSTOMER = 'ADD_ACTIVE_CUSTOMER';
export const DELETE_ACTIVE_CUSTOMER = 'DELETE_ACTIVE_CUSTOMER';
export const EDIT_ACTIVE_CUSTOMER = 'EDIT_ACTIVE_CUSTOMER';
export const GET_ACTIVE_CUSTOMER = 'GET_ACTIVE_CUSTOMER'
