export const GET_ACTIVE_SUPPLIERS = 'GET_ACTIVE_SUPPLIERS';
export const DELETE_ACTIVE_SUPPLIER = 'DELETE_ACTIVE_SUPPLIER';
export const GET_ACTIVE_SUPPLIER = 'GET_ACTIVE_SUPPLIER';
export const ADD_ACTIVE_SUPPLIER = 'ADD_ACTIVE_SUPPLIER';
