export const ADD_AUTHORISED_EMPLOYEE_LEAVE = 'ADD_AUTHORISED_EMPLOYEE_LEAVE';
export const GET_AUTHORISED_EMPLOYEE_LEAVES = 'GET_AUTHORISED_EMPLOYEE_LEAVES';
export const DELETE_AUTHORISED_EMPLOYEE_LEAVE = 'DELETE_AUTHORISED_EMPLOYEE_LEAVE';
export const GET_AUTHORISED_EMPLOYEE_LEAVE = 'GET_AUTHORISED_EMPLOYEE_LEAVE';
