export const GET_BILL_PAYMENTS = 'GET_BILL_PAYMENTS';
export const DELETE_BILL_PAYMENT = 'DELETE_BILL_PAYMENT';
export const ADD_BILL_PAYMENT = 'ADD_BILL_PAYMENT';
export const GET_BILL_PAYMENT = 'GET_BILL_PAYMENT'
