export const GET_PRODUCT_STATUS_CHOICES = "GET_PRODUCT_STATUS_CHOICES";
export const GET_HAULIER_STATUS_CHOICES = "GET_HAULIER_STATUS_CHOICES";
export const GET_CUSTOMER_STATUS_CHOICES = "GET_CUSTOMER_STATUS_CHOICES";
export const GET_TRANSACTION_STATUS_CHOICES = "GET_TRANSACTION_STATUS_CHOICES";
export const GET_TRANSACTION_TYPE_CHOICES = "GET_TRANSACTION_TYPE_CHOICES";



