export const GET_COMPLETED_EVENTS = 'GET_COMPLETED_EVENTS';
export const DELETE_COMPLETED_EVENT = 'DELETE_COMPLETED_EVENT';
export const ADD_COMPLETED_EVENT = 'ADD_COMPLETED_EVENT';
export const GET_COMPLETED_EVENT = 'GET_COMPLETED_EVENT';
