export const ADD_COMPANY_PAYROLL_OFFICER = 'ADD_COMPANY_PAYROLL_OFFICER';
export const GET_COMPANY_PAYROLL_OFFICERS = 'GET_COMPANY_PAYROLL_OFFICERS';
export const DELETE_COMPANY_PAYROLL_OFFICER = 'DELETE_COMPANY_PAYROLL_OFFICER';
export const GET_COMPANY_PAYROLL_OFFICER = 'GET_COMPANY_PAYROLL_OFFICER';
