export const ADD_COMPANY_DRIVER = 'ADD_COMPANY_DRIVER';
export const GET_COMPANY_DRIVERS = 'GET_COMPANY_DRIVERS';
export const DELETE_COMPANY_DRIVER = 'DELETE_COMPANY_DRIVER';
export const GET_COMPANY_DRIVER = 'GET_COMPANY_DRIVER';
