export const ADD_COMPANY_BOOKKEEPER = 'ADD_COMPANY_BOOKKEEPER';
export const GET_COMPANY_BOOKKEEPERS = 'GET_COMPANY_BOOKKEEPERS';
export const DELETE_COMPANY_BOOKKEEPER = 'DELETE_COMPANY_BOOKKEEPER';
export const GET_COMPANY_BOOKKEEPER = 'GET_COMPANY_BOOKKEEPER';
