export const ADD_COMPANY_SHAREHOLDER = 'ADD_COMPANY_SHAREHOLDER';
export const GET_COMPANY_SHAREHOLDERS = 'GET_COMPANY_SHAREHOLDERS';
export const DELETE_COMPANY_SHAREHOLDER = 'DELETE_COMPANY_SHAREHOLDER';
export const GET_COMPANY_SHAREHOLDER = 'GET_COMPANY_SHAREHOLDER';
