export const ADD_COMPANY_MANAGER = 'ADD_COMPANY_MANAGER';
export const GET_COMPANY_MANAGERS = 'GET_COMPANY_MANAGERS';
export const DELETE_COMPANY_MANAGER = 'DELETE_COMPANY_MANAGER';
export const GET_COMPANY_MANAGER = 'GET_COMPANY_MANAGER';
