export const ADD_COMPANY_INVENTORY_CONTROLLER = 'ADD_COMPANY_INVENTORY_CONTROLLER';
export const GET_COMPANY_INVENTORY_CONTROLLERS = 'GET_COMPANY_INVENTORY_CONTROLLERS';
export const DELETE_COMPANY_INVENTORY_CONTROLLER = 'DELETE_COMPANY_INVENTORY_CONTROLLER';
export const GET_COMPANY_INVENTORY_CONTROLLER = 'GET_COMPANY_INVENTORY_CONTROLLER';
