export const ADD_COMPANY_SALESREP = 'ADD_COMPANY_SALESREP';
export const GET_COMPANY_SALESREPS = 'GET_COMPANY_SALESREPS';
export const DELETE_COMPANY_SALESREP = 'DELETE_COMPANY_SALESREP';
export const GET_COMPANY_SALESREP = 'GET_COMPANY_SALESREP';
