export const GET_COMPANY_BRANCHES = "GET_COMPANY_BRANCHES";
export const GET_COMPANY_BRANCH = "GET_COMPANY_BRANCH";
export const ADD_COMPANY_BRANCH = "ADD_COMPANY_BRANCH";
export const EDIT_COMPANY_BRANCH = "EDIT_COMPANY_BRANCH";
export const DELETE_COMPANY_BRANCH = "DELETE_COMPANY_BRANCH";
