export const GET_CONSUMABLES = 'GET_CONSUMABLES';
export const DELETE_CONSUMABLE = 'DELETE_CONSUMABLE';
export const ADD_CONSUMABLE = 'ADD_CONSUMABLE';
export const GET_CONSUMABLE = 'GET_CONSUMABLE';
