export const GET_CREDIT_NOTES = 'GET_CREDIT_NOTES';
export const DELETE_CREDIT_NOTE = 'DELETE_CREDIT_NOTE';
export const ADD_CREDIT_NOTE = 'ADD_CREDIT_NOTE';
export const GET_CREDIT_NOTE = 'GET_CREDIT_NOTE';
