export const GET_CURRENCIES_START = 'GET_CURRENCIES_START';
export const GET_CURRENCIES_SUCCESS = 'GET_CURRENCIES_SUCCESS';
export const GET_CURRENCIES_FAIL = 'GET_CURRENCIES_FAIL';
export const CREATE_CURRENCY_START = 'CREATE_CURRENCY_START';
export const CREATE_CURRENCY_SUCCESS = 'CREATE_CURRENCY_SUCCESS';
export const CREATE_CURRENCY_FAIL = 'CREATE_CURRENCY_FAIL';
export const EDIT_CURRENCY = 'EDIT_CURRENCY'