export const ADD_CUSTOMER_ADDRESS = 'ADD_CUSTOMER_ADDRESS';
export const GET_CUSTOMER_ADDRESSES = 'GET_CUSTOMER_ADDRESSES';
export const DELETE_CUSTOMER_ADDRESS = 'DELETE_CUSTOMER_ADDRESS';
export const GET_CUSTOMER_ADDRESS = 'GET_CUSTOMER_ADDRESS';
