export const GET_DEACTIVED_SUPPLIERS_START = 'GET_DEACTIVED_SUPPLIERS_START';
export const GET_DEACTIVED_SUPPLIERS_SUCCESS = 'GET_DEACTIVED_SUPPLIERS_SUCCESS';
export const GET_DEACTIVED_SUPPLIERS_FAIL = 'GET_DEACTIVED_SUPPLIERS_FAIL'