export const GET_DE_ACTIVED_SUPPLIERS = 'GET_DE_ACTIVED_SUPPLIERS';
export const DELETE_DE_ACTIVED_SUPPLIER = 'DELETE_DE_ACTIVED_SUPPLIER';
export const GET_DE_ACTIVED_SUPPLIER = 'GET_DE_ACTIVED_SUPPLIER';
