export const GET_DEACTIVATED_CUSTOMERS_START = 'GET_DEACTIVATED_CUSTOMERS_START';
export const GET_DEACTIVATED_CUSTOMERS_SUCCESS = 'GET_DEACTIVATED_CUSTOMERS_SUCCESS';
export const GET_DEACTIVATED_CUSTOMERS_FAIL = 'GET_DEACTIVATED_CUSTOMERS_FAIL'