export const ADD_DECLINED_EMPLOYEE_LEAVE = 'ADD_DECLINED_EMPLOYEE_LEAVE';
export const GET_DECLINED_EMPLOYEE_LEAVES = 'GET_DECLINED_EMPLOYEE_LEAVES';
export const DELETE_DECLINED_EMPLOYEE_LEAVE = 'DELETE_DECLINED_EMPLOYEE_LEAVE';
export const GET_DECLINED_EMPLOYEE_LEAVE = 'GET_DECLINED_EMPLOYEE_LEAVE';
