export const ADD_EMPLOYEE_PAYROLL_DATE = "ADD_EMPLOYEE_PAYROLL_DATE"; 
export const GET_EMPLOYEE_PAYROLL_DATES = "GET_EMPLOYEE_PAYROLL_DATES"; 
export const GET_EMPLOYEE_PAYROLL_DATE = "GET_EMPLOYEE_PAYROLL_DATE"; 
export const DELETE_EMPLOYEE_PAYROLL_DATE = "DELETE_EMPLOYEE_PAYROLL_DATE";
