export const ADD_EMPLOYEE_PAYROLL_SCHEDULE = "ADD_EMPLOYEE_PAYROLL_SCHEDULE"; 
export const GET_EMPLOYEE_PAYROLL_SCHEDULES = "GET_EMPLOYEE_PAYROLL_SCHEDULES"; 
export const GET_EMPLOYEE_PAYROLL_SCHEDULE = "GET_EMPLOYEE_PAYROLL_SCHEDULE"; 
export const DELETE_EMPLOYEE_PAYROLL_SCHEDULE = "DELETE_EMPLOYEE_PAYROLL_SCHEDULE";
