export const ADD_EMPLOYEE_LEAVE = "ADD_EMPLOYEE_LEAVE"; 
export const GET_EMPLOYEE_LEAVES = "GET_EMPLOYEE_LEAVES"; 
export const GET_EMPLOYEE_LEAVE = "GET_EMPLOYEE_LEAVE"; 
export const DELETE_EMPLOYEE_LEAVE = "DELETE_EMPLOYEE_LEAVE";
