export const ADD_EMPLOYEE_PAYROLL_TAX = "ADD_EMPLOYEE_PAYROLL_TAX";
export const GET_EMPLOYEE_PAYROLL_TAXES = "GET_EMPLOYEE_PAYROLL_TAXES";
export const GET_EMPLOYEE_PAYROLL_TAX = "GET_EMPLOYEE_PAYROLL_TAX";
export const DELETE_EMPLOYEE_PAYROLL_TAX = "DELETE_EMPLOYEE_PAYROLL_TAX";
export const EDIT_EMPLOYEE_PAYROLL_TAX = "EDIT_EMPLOYEE_PAYROLL_TAX";
