export const ADD_EMPLOYEE_ATTENDANCE_TIMESHEET = "ADD_EMPLOYEE_ATTENDANCE_TIMESHEET"; 
export const GET_EMPLOYEE_ATTENDANCE_TIMESHEETS = "GET_EMPLOYEE_ATTENDANCE_TIMESHEETS"; 
export const GET_EMPLOYEE_ATTENDANCE_TIMESHEET = "GET_EMPLOYEE_ATTENDANCE_TIMESHEET"; 
export const DELETE_EMPLOYEE_ATTENDANCE_TIMESHEET = "DELETE_EMPLOYEE_ATTENDANCE_TIMESHEET";
