export const ADD_EMPLOYEE_PAYGRADE = "ADD_EMPLOYEE_PAYGRADE";
export const GET_EMPLOYEE_PAYGRADES = "GET_EMPLOYEE_PAYGRADES";
export const GET_EMPLOYEE_PAYGRADE = "GET_EMPLOYEE_PAYGRADE";
export const DELETE_EMPLOYEE_PAYGRADE = "DELETE_EMPLOYEE_PAYGRADE";
export const EDIT_EMPLOYEE_PAYGRADE = "EDIT_EMPLOYEE_PAYGRADE";
