export const ADD_EMPLOYEE_PAY_COMMISSION_RULE = "ADD_EMPLOYEE_PAY_COMMISSION_RULE";
export const GET_EMPLOYEE_PAY_COMMISSION_RULES = "GET_EMPLOYEE_PAY_COMMISSION_RULES";
export const GET_EMPLOYEE_PAY_COMMISSION_RULE = "GET_EMPLOYEE_PAY_COMMISSION_RULE";
export const DELETE_EMPLOYEE_PAY_COMMISSION_RULE = "DELETE_EMPLOYEE_PAY_COMMISSION_RULE";
export const EDIT_EMPLOYEE_PAY_COMMISSION_RULE = "EDIT_EMPLOYEE_PAY_COMMISSION_RULE";
