export const ADD_EMPLOYEE_PAY_DEDUCTION = "ADD_EMPLOYEE_PAY_DEDUCTION"; 
export const GET_EMPLOYEE_PAY_DEDUCTIONS = "GET_EMPLOYEE_PAY_DEDUCTIONS"; 
export const GET_EMPLOYEE_PAY_DEDUCTION = "GET_EMPLOYEE_PAY_DEDUCTION"; 
export const DELETE_EMPLOYEE_PAY_DEDUCTION = "DELETE_EMPLOYEE_PAY_DEDUCTION";
