export const ADD_EMPLOYEE_CONTRACT = "ADD_EMPLOYEE_CONTRACT"; 
export const GET_EMPLOYEE_CONTRACTS = "GET_EMPLOYEE_CONTRACTS"; 
export const GET_EMPLOYEE_CONTRACT = "GET_EMPLOYEE_CONTRACT"; 
export const DELETE_EMPLOYEE_CONTRACT = "DELETE_EMPLOYEE_CONTRACT";
