export const CREATE_EMPLOYEE_CONFIG_START = 'CREATE_EMPLOYEE_CONFIG_START';
export const CREATE_EMPLOYEE_CONFIG_SUCCESS = 'CREATE_EMPLOYEE_CONFIG_SUCCESS';
export const CREATE_EMPLOYEE_CONFIG_FAIL = 'CREATE_EMPLOYEE_CONFIG_FAIL'