export const ADD_EMPLOYEE_ALLOWANCE = "ADD_EMPLOYEE_ALLOWANCE"; 
export const GET_EMPLOYEE_ALLOWANCES = "GET_EMPLOYEE_ALLOWANCES"; 
export const GET_EMPLOYEE_ALLOWANCE = "GET_EMPLOYEE_ALLOWANCE"; 
export const DELETE_EMPLOYEE_ALLOWANCE = "DELETE_EMPLOYEE_ALLOWANCE";
