export const ADD_EMPLOYEE_PAYSLIP = "ADD_EMPLOYEE_PAYSLIP"; 
export const GET_EMPLOYEE_PAYSLIPS = "GET_EMPLOYEE_PAYSLIPS"; 
export const GET_EMPLOYEE_PAYSLIP = "GET_EMPLOYEE_PAYSLIP"; 
export const DELETE_EMPLOYEE_PAYSLIP = "DELETE_EMPLOYEE_PAYSLIP";
