export const ADD_EMPLOYEE_DEPARTMENT = "ADD_EMPLOYEE_DEPARTMENT";
export const GET_EMPLOYEE_DEPARTMENTS = "GET_EMPLOYEE_DEPARTMENTS";
export const GET_EMPLOYEE_DEPARTMENT = "GET_EMPLOYEE_DEPARTMENT";
export const DELETE_EMPLOYEE_DEPARTMENT = "DELETE_EMPLOYEE_DEPARTMENT";
export const EDIT_EMPLOYEE_DEPARTMENT = "EDIT_EMPLOYEE_DEPARTMENT";
