export const GET_EQUIPMENTS = 'GET_EQUIPMENTS';
export const DELETE_EQUIPMENT = 'DELETE_EQUIPMENT';
export const ADD_EQUIPMENT = 'ADD_EQUIPMENT';
export const GET_EQUIPMENT = 'GET_EQUIPMENT';
export const EDIT_EQUIPMENT = 'EDIT_EQUIPMENT';
