export const CREATE_EVENT_CONFIG_START = 'CREATE_EVENT_CONFIG_START';
export const CREATE_EVENT_CONFIG_SUCCESS = 'CREATE_EVENT_CONFIG_SUCCESS';
export const CREATE_EVENT_CONFIG_FAIL = 'CREATE_EVENT_CONFIG_FAIL'