export const GET_FULLY_PAID_BILLS_START = 'GET_FULLY_PAID_BILLS_START';
export const GET_FULLY_PAID_BILLS_SUCCESS = 'GET_FULLY_PAID_BILLS_SUCCESS';
export const GET_FULLY_PAID_BILLS_FAIL = 'GET_FULLY_PAID_BILLS_FAIL';
export const GET_FULLY_PAID_BILL_START = 'GET_FULLY_PAID_BILL_START';
export const GET_FULLY_PAID_BILL_SUCCESS = 'GET_FULLY_PAID_BILL_SUCCESS';
export const GET_FULLY_PAID_BILL_FAIL = 'GET_FULLY_PAID_BILL_FAIL'