export const GET_IN_ACTIVE_ACCOUNTS_START = 'GET_IN_ACTIVE_ACCOUNTS_START';
export const GET_IN_ACTIVE_ACCOUNTS_SUCCESS = 'GET_IN_ACTIVE_ACCOUNTS_SUCCESS';
export const GET_IN_ACTIVE_ACCOUNTS_FAIL = 'GET_IN_ACTIVE_ACCOUNTS_FAIL';
export const GET_IN_ACTIVE_ACCOUNT_START = 'GET_IN_ACTIVE_ACCOUNT_START';
export const GET_IN_ACTIVE_ACCOUNT_SUCCESS = 'GET_IN_ACTIVE_ACCOUNT_SUCCESS';
export const GET_IN_ACTIVE_ACCOUNT_FAIL = 'GET_IN_ACTIVE_ACCOUNT_FAIL'