export const ADD_INTEREST_BEARING_ACCOUNT = 'ADD_INTEREST_BEARING_ACCOUNT';
export const GET_INTEREST_BEARING_ACCOUNTS = 'GET_INTEREST_BEARING_ACCOUNTS';
export const DELETE_INTEREST_BEARING_ACCOUNT = 'DELETE_INTEREST_BEARING_ACCOUNT';
export const GET_INTEREST_BEARING_ACCOUNT = 'GET_INTEREST_BEARING_ACCOUNT';
export const EDIT_INTEREST_BEARING_ACCOUNT = 'EDIT_INTEREST_BEARING_ACCOUNT'
