export const GET_INVENTORY_ORDERS = 'GET_INVENTORY_ORDERS';
export const DELETE_INVENTORY_ORDER = 'DELETE_INVENTORY_ORDER';
export const ADD_INVENTORY_ORDER = 'ADD_INVENTORY_ORDER';
export const GET_INVENTORY_ORDER = 'GET_INVENTORY_ORDER';
