export const GET_INVENTORY_STOCK_ITEMS = 'GET_INVENTORY_STOCK_ITEMS';
export const DELETE_INVENTORY_STOCK_ITEM = 'DELETE_INVENTORY_STOCK_ITEM';
export const ADD_INVENTORY_STOCK_ITEM = 'ADD_INVENTORY_STOCK_ITEM';
export const GET_INVENTORY_STOCK_ITEM = 'GET_INVENTORY_STOCK_ITEM';
export const EDIT_INVENTORY_STOCK_ITEM = 'EDIT_INVENTORY_STOCK_ITEM';
