export const GET_INVENTORY_CATEGORIES = 'GET_INVENTORY_CATEGORIES';
export const DELETE_INVENTORY_CATEGORY = 'DELETE_INVENTORY_CATEGORY';
export const ADD_INVENTORY_CATEGORY = 'ADD_INVENTORY_CATEGORY';
export const GET_INVENTORY_CATEGORY = 'GET_INVENTORY_CATEGORY';
