export const GET_INVENTORY_ORDERPAYMENTS = 'GET_INVENTORY_ORDERPAYMENTS';
export const DELETE_INVENTORY_ORDERPAYMENT = 'DELETE_INVENTORY_ORDERPAYMENT';
export const ADD_INVENTORY_ORDERPAYMENT = 'ADD_INVENTORY_ORDERPAYMENT';
export const GET_INVENTORY_ORDERPAYMENT = 'GET_INVENTORY_ORDERPAYMENT';
export const EDIT_INVENTORY_ORDERPAYMENT = 'EDIT_INVENTORY_ORDERPAYMENT';
