export const GET_JOURNALS_START = 'GET_JOURNALS_START';
export const GET_JOURNALS_SUCCESS = 'GET_JOURNALS_SUCCESS';
export const GET_JOURNALS_FAIL = 'GET_JOURNALS_FAIL';
export const GET_JOURNAL_START = 'GET_JOURNAL_START';
export const GET_JOURNAL_SUCCESS = 'GET_JOURNAL_SUCCESS';
export const GET_JOURNAL_FAIL = 'GET_JOURNAL_FAIL';