export const ADD_MANUFACTURING_PERSONEL = "ADD_MANUFACTURING_PERSONEL";
export const GET_MANUFACTURING_PERSONELS = "GET_MANUFACTURING_PERSONELS";
export const GET_MANUFACTURING_PERSONEL = "GET_MANUFACTURING_PERSONEL";
export const DELETE_MANUFACTURING_PERSONEL = "DELETE_MANUFACTURING_PERSONEL";
export const EDIT_MANUFACTURING_PERSONEL = "EDIT_MANUFACTURING_PERSONEL";
