export const ADD_MANUFACTURING_TEAM = "ADD_MANUFACTURING_TEAM"; 
export const GET_MANUFACTURING_TEAMS = "GET_MANUFACTURING_TEAMS"; 
export const GET_MANUFACTURING_TEAM = "GET_MANUFACTURING_TEAM"; 
export const DELETE_MANUFACTURING_TEAM = "DELETE_MANUFACTURING_TEAM";
