export const ADD_MANUFACTURED_STOCK_ITEM = 'ADD_MANUFACTURED_STOCK_ITEM';
export const GET_MANUFACTURED_STOCK_ITEMS = 'GET_MANUFACTURED_STOCK_ITEMS';
export const DELETE_MANUFACTURED_STOCK_ITEM = 'DELETE_MANUFACTURED_STOCK_ITEM';
export const GET_MANUFACTURED_STOCK_ITEM = 'GET_MANUFACTURED_STOCK_ITEM';
