export const GET_OVERDUE_INVOICES_START = 'GET_OVERDUE_INVOICES_START';
export const GET_OVERDUE_INVOICES_SUCCESS = 'GET_OVERDUE_INVOICES_SUCCESS';
export const GET_OVERDUE_INVOICES_FAIL = 'GET_OVERDUE_INVOICES_FAIL';
export const GET_OVERDUE_INVOICE_START = 'GET_OVERDUE_INVOICE_START';
export const GET_OVERDUE_INVOICE_SUCCESS = 'GET_OVERDUE_INVOICE_SUCCESS';
export const GET_OVERDUE_INVOICE_FAIL = 'GET_OVERDUE_INVOICE_FAIL';