export const ADD_PENDING_EMPLOYEE_LEAVE = 'ADD_PENDING_EMPLOYEE_LEAVE';
export const GET_PENDING_EMPLOYEE_LEAVES = 'GET_PENDING_EMPLOYEE_LEAVES';
export const DELETE_PENDING_EMPLOYEE_LEAVE = 'DELETE_PENDING_EMPLOYEE_LEAVE';
export const GET_PENDING_EMPLOYEE_LEAVE = 'GET_PENDING_EMPLOYEE_LEAVE';
