export const GET_POSTED_JOURNAL_ENTRIES = 'GET_POSTED_JOURNAL_ENTRIES';
export const DELETE_POSTED_JOURNAL_ENTRY = 'DELETE_POSTED_JOURNAL_ENTRY';
export const GET_POSTED_JOURNAL_ENTRY = 'GET_POSTED_JOURNAL_ENTRY'
