export const GET_PROCESS_MACHINE_GROUPS = 'GET_PROCESS_MACHINE_GROUPS';
export const DELETE_PROCESS_MACHINE_GROUP = 'DELETE_PROCESS_MACHINE_GROUP';
export const ADD_PROCESS_MACHINE_GROUP = 'ADD_PROCESS_MACHINE_GROUP';
export const GET_PROCESS_MACHINE_GROUP = 'GET_PROCESS_MACHINE_GROUP';
