export const GET_PROCESS_PRODUCTS = 'GET_PROCESS_PRODUCTS';
export const DELETE_PROCESS_PRODUCT = 'DELETE_PROCESS_PRODUCT';
export const ADD_PROCESS_PRODUCT = 'ADD_PROCESS_PRODUCT';
export const GET_PROCESS_PRODUCT = 'GET_PROCESS_PRODUCT';
