export const GET_PROCESS_RATES = 'GET_PROCESS_RATES';
export const DELETE_PROCESS_RATE = 'DELETE_PROCESS_RATE';
export const ADD_PROCESS_RATE = 'ADD_PROCESS_RATE';
export const GET_PROCESS_RATE = 'GET_PROCESS_RATE';
export const EDIT_PROCESS_RATE = 'EDIT_PROCESS_RATE';
