export const GET_PROCESS_MACHINES = 'GET_PROCESS_MACHINES';
export const DELETE_PROCESS_MACHINE = 'DELETE_PROCESS_MACHINE';
export const ADD_PROCESS_MACHINE = 'ADD_PROCESS_MACHINE';
export const GET_PROCESS_MACHINE = 'GET_PROCESS_MACHINE';
