export const ADD_PROCESSED_PRODUCT_STOCK_TAKE = "ADD_PROCESSED_PRODUCT_STOCK_TAKE";
export const GET_PROCESSED_PRODUCT_STOCK_TAKES = "GET_PROCESSED_PRODUCT_STOCK_TAKES";
export const GET_PROCESSED_PRODUCT_STOCK_TAKE = "GET_PROCESSED_PRODUCT_STOCK_TAKE";
export const DELETE_PROCESSED_PRODUCT_STOCK_TAKE = "DELETE_PROCESSED_PRODUCT_STOCK_TAKE";
