export const ADD_PROCESSED_PRODUCT_STOCK_RECEIPT = "ADD_PROCESSED_PRODUCT_STOCK_RECEIPT"; 
export const GET_PROCESSED_PRODUCT_STOCK_RECEIPTS = "GET_PROCESSED_PRODUCT_STOCK_RECEIPTS"; 
export const GET_PROCESSED_PRODUCT_STOCK_RECEIPT = "GET_PROCESSED_PRODUCT_STOCK_RECEIPT";
export const DELETE_PROCESSED_PRODUCT_STOCK_RECEIPT = "DELETE_PROCESSED_PRODUCT_STOCK_RECEIPT";
