export const GET_PRODUCTION_ORDERS = 'GET_PRODUCTION_ORDERS';
export const DELETE_PRODUCTION_ORDER = 'DELETE_PRODUCTION_ORDER';
export const ADD_PRODUCTION_ORDER = 'ADD_PRODUCTION_ORDER';
export const GET_PRODUCTION_ORDER = 'GET_PRODUCTION_ORDER';
