export const GET_QUOTATIONS_START = 'GET_QUOTATIONS_START';
export const GET_QUOTATIONS_SUCCESS = 'GET_QUOTATIONS_SUCCESS';
export const GET_QUOTATIONS_FAIL = 'GET_QUOTATIONS_FAIL';
export const GET_QUOTATION_START = 'GET_QUOTATION_START';
export const GET_QUOTATION_SUCCESS = 'GET_QUOTATION_SUCCESS';
export const GET_QUOTATION_FAIL = 'GET_QUOTATION_FAIL';