export const GET_RAW_MATERIALS = 'GET_RAW_MATERIALS';
export const DELETE_RAW_MATERIAL = 'DELETE_RAW_MATERIAL';
export const ADD_RAW_MATERIAL = 'ADD_RAW_MATERIAL';
export const GET_RAW_MATERIAL = 'GET_RAW_MATERIAL';
