export const GET_RECEIPTS_START = 'GET_RECEIPTS_START';
export const GET_RECEIPTS_SUCCESS = 'GET_RECEIPTS_SUCCESS';
export const GET_RECEIPTS_FAIL = 'GET_RECEIPTS_FAIL';
export const GET_RECEIPT_START = 'GET_RECEIPT_START';
export const GET_RECEIPT_SUCCESS = 'GET_RECEIPT_SUCCESS';
export const GET_RECEIPT_FAIL = 'GET_RECEIPT_FAIL';