export const GET_REFUNDED_INVOICES_START = 'GET_REFUNDED_INVOICES_START';
export const GET_REFUNDED_INVOICES_SUCCESS = 'GET_REFUNDED_INVOICES_SUCCESS';
export const GET_REFUNDED_INVOICES_FAIL = 'GET_REFUNDED_INVOICES_FAIL';
export const GET_REFUNDED_INVOICE_START = 'GET_REFUNDED_INVOICE_START';
export const GET_REFUNDED_INVOICE_SUCCESS = 'GET_REFUNDED_INVOICE_SUCCESS';
export const GET_REFUNDED_INVOICE_FAIL = 'GET_REFUNDED_INVOICE_FAIL';