export const GET_SALES_GROUPS_PRICING_DISCOUNTS = 'GET_SALES_GROUPS_PRICING_DISCOUNTS';
export const DELETE_SALES_GROUPS_PRICING_DISCOUNT = 'DELETE_SALES_GROUPS_PRICING_DISCOUNT';
export const ADD_SALES_GROUPS_PRICING_DISCOUNT = 'ADD_SALES_GROUPS_PRICING_DISCOUNT';
export const GET_SALES_GROUPS_PRICING_DISCOUNT = 'GET_SALES_GROUPS_PRICING_DISCOUNT';
