export const ADD_SHIFT_SCHEDULE = 'ADD_SHIFT_SCHEDULE';
export const GET_SHIFT_SCHEDULES = 'GET_SHIFT_SCHEDULES';
export const DELETE_SHIFT_SCHEDULE = 'DELETE_SHIFT_SCHEDULE'
export const GET_SHIFT_SCHEDULE = 'GET_SHIFT_SCHEDULE';
export const EDIT_SHIFT_SCHEDULE = 'EDIT_SHIFT_SCHEDULE';
