export const ADD_SUPPLIER_ADDRESS = 'ADD_SUPPLIER_ADDRESS';
export const GET_SUPPLIER_ADDRESSES = 'GET_SUPPLIER_ADDRESSES';
export const DELETE_SUPPLIER_ADDRESS = 'DELETE_SUPPLIER_ADDRESS';
export const GET_SUPPLIER_ADDRESS = 'GET_SUPPLIER_ADDRESS';
export const EDIT_SUPPLIER_ADDRESS = 'EDIT_SUPPLIER_ADDRESS';
