export const CREATE_TAX_START = 'CREATE_TAX_START';
export const CREATE_TAX_SUCCESS = 'CREATE_TAX_SUCCESS';
export const CREATE_TAX_FAIL = 'CREATE_TAX_FAIL';
export const EDIT_TAX = 'EDIT_TAX';
export const GET_TAXES_START = 'GET_TAXES_START';
export const GET_TAXES_SUCCESS = 'GET_TAXES_SUCCESS';
export const GET_TAXES_FAIL = 'GET_TAXES_FAIL';