

export const GET_ONETIER_TRANSACTIONS_ADMIN_VIEW = "GET_ONETIER_TRANSACTIONS_ADMIN_VIEW";
export const GET_ONETIER_TRANSACTION_ADMIN_VIEW = "GET_ONETIER_TRANSACTION_ADMIN_VIEW";
export const EDIT_ONETIER_TRANSACTION_ADMIN_VIEW = "EDIT_ONETIER_TRANSACTION_ADMIN_VIEW";
export const ADD_ONETIER_TRANSACTION_ADMIN_VIEW = "ADD_ONETIER_TRANSACTION_ADMIN_VIEW";
export const GET_TWOTIER_TRANSACTIONS_ADMIN_VIEW = "GET_TWOTIER_TRANSACTIONS_ADMIN_VIEW";
export const GET_TWOTIER_TRANSACTION_ADMIN_VIEW = "GET_TWOTIER_TRANSACTION_ADMIN_VIEW";
export const EDIT_TWOTIER_TRANSACTION_ADMIN_VIEW = "EDIT_TWOTIER_TRANSACTION_ADMIN_VIEW";
export const ADD_TWOTIER_TRANSACTION_ADMIN_VIEW = "ADD_TWOTIER_TRANSACTION_ADMIN_VIEW";
export const GET_CANCELLED_TRANSACTIONS_ADMIN_VIEW = "GET_CANCELLED_TRANSACTIONS_ADMIN_VIEW";
export const GET_ARCHIVED_TRANSACTIONS_ADMIN_VIEW = "GET_ARCHIVED_TRANSACTIONS_ADMIN_VIEW";
export const GET_CANCELLED_TRANSACTION_ADMIN_VIEW = "GET_CANCELLED_TRANSACTION_ADMIN_VIEW";
export const GET_ARCHIVED_TRANSACTION_ADMIN_VIEW = "GET_ARCHIVED_TRANSACTION_ADMIN_VIEW";
export const GET_LOADING_POINTS = "GET_LOADING_POINTS";
export const ADD_LOADING_POINT = "ADD_LOADING_POINT";
export const EDIT_LOADING_POINT = "EDIT_LOADING_POINT";



