export const GET_UNPOSTED_JOURNAL_ENTRIES_START = 'GET_UNPOSTED_JOURNAL_ENTRIES_START';
export const GET_UNPOSTED_JOURNAL_ENTRIES_SUCCESS = 'GET_UNPOSTED_JOURNAL_ENTRIES_SUCCESS';
export const GET_UNPOSTED_JOURNAL_ENTRIES_FAIL = 'GET_UNPOSTED_JOURNAL_ENTRIES_FAIL';
export const GET_UNPOSTED_JOURNAL_ENTRY_START = 'GET_UNPOSTED_JOURNAL_ENTRY_START';
export const GET_UNPOSTED_JOURNAL_ENTRY_SUCCESS = 'GET_UNPOSTED_JOURNAL_ENTRY_SUCCESS';
export const GET_UNPOSTED_JOURNAL_ENTRY_FAIL = 'GET_UNPOSTED_JOURNAL_ENTRY_FAIL';