export const GET_UNVERIFIED_INVOICES_START = 'GET_UNVERIFIED_INVOICES_START';
export const GET_UNVERIFIED_INVOICES_SUCCESS = 'GET_UNVERIFIED_INVOICES_SUCCESS';
export const GET_UNVERIFIED_INVOICES_FAIL = 'GET_UNVERIFIED_INVOICES_FAIL';
export const GET_UNVERIFIED_INVOICE_START = 'GET_UNVERIFIED_INVOICE_START';
export const GET_UNVERIFIED_INVOICE_SUCCESS = 'GET_UNVERIFIED_INVOICE_SUCCESS';
export const GET_UNVERIFIED_INVOICE_FAIL = 'GET_UNVERIFIED_INVOICE_FAIL';