export const GET_UPCOMING_EVENTS = 'GET_UPCOMING_EVENTS';
export const DELETE_UPCOMING_EVENT = 'DELETE_UPCOMING_EVENT';
export const ADD_UPCOMING_EVENT = 'ADD_UPCOMING_EVENT';
export const GET_UPCOMING_EVENT = 'GET_UPCOMING_EVENT';
