export const GET_VERIFIED_PRODUCTION_PROCESSES = 'GET_VERIFIED_PRODUCTION_PROCESSES';
export const DELETE_VERIFIED_PRODUCTION_PROCESS = 'DELETE_VERIFIED_PRODUCTION_PROCESS';
export const GET_VERIFIED_PRODUCTION_PROCESS = 'GET_VERIFIED_PRODUCTION_PROCESS'
