export const GET_VOIDED_INVOICES_START = 'GET_VOIDED_INVOICES_START';
export const GET_VOIDED_INVOICES_SUCCESS = 'GET_VOIDED_INVOICES_SUCCESS';
export const GET_VOIDED_INVOICES_FAIL = 'GET_VOIDED_INVOICES_FAIL';
export const GET_VOIDED_INVOICE_START = 'GET_VOIDED_INVOICE_START';
export const GET_VOIDED_INVOICE_SUCCESS = 'GET_VOIDED_INVOICE_SUCCESS';
export const GET_VOIDED_INVOICE_FAIL = 'GET_VOIDED_INVOICE_FAIL';