export const GET_WASTE_GENERATION_REPORTS = 'GET_WASTE_GENERATION_REPORTS';
export const DELETE_WASTE_GENERATION_REPORT = 'DELETE_WASTE_GENERATION_REPORT';
export const ADD_WASTE_GENERATION_REPORT = 'ADD_WASTE_GENERATION_REPORT';
export const GET_WASTE_GENERATION_REPORT = 'GET_WASTE_GENERATION_REPORT';
