# Generated by Django 3.0.7 on 2020-09-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20200902_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='is_admin',
            new_name='admin',
        ),
        migrations.AddField(
            model_name='employee',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
