# Generated by Django 3.0.7 on 2020-08-18 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=120)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=120, null=True, verbose_name='organ code')),
                ('name', models.CharField(max_length=120, verbose_name='organ name')),
                ('short', models.CharField(blank=True, max_length=120, null=True, verbose_name='short name')),
                ('status', models.BooleanField(default=True, verbose_name='in use')),
                ('tax_num', models.CharField(blank=True, max_length=120, null=True, verbose_name='tax num')),
                ('tax_address', models.CharField(blank=True, max_length=120, null=True, verbose_name='tax address')),
                ('tax_account', models.CharField(blank=True, max_length=120, null=True, verbose_name='tax account')),
                ('represent', models.CharField(blank=True, max_length=120, null=True, verbose_name='representative ')),
                ('address', models.CharField(blank=True, max_length=120, null=True, verbose_name='address')),
                ('zipcode', models.CharField(blank=True, max_length=120, null=True, verbose_name='zipcode')),
                ('fax', models.CharField(blank=True, max_length=120, null=True, verbose_name='fax')),
                ('contacts', models.CharField(blank=True, max_length=120, null=True, verbose_name='contacts')),
                ('phone', models.CharField(blank=True, max_length=120, null=True, verbose_name='phone')),
                ('website', models.CharField(blank=True, max_length=120, null=True, verbose_name='website')),
                ('email', models.CharField(blank=True, max_length=120, null=True, verbose_name='email')),
                ('lic_code', models.CharField(blank=True, max_length=120, null=True, verbose_name='license code')),
                ('cer_code', models.CharField(blank=True, max_length=120, null=True, verbose_name='certificate code')),
                ('license', models.FileField(blank=True, null=True, upload_to='organ', verbose_name='business license')),
                ('logo', models.FileField(blank=True, null=True, upload_to='organ', verbose_name='business license')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='organ', verbose_name='organization code certificate')),
                ('weight', models.IntegerField(default=9, verbose_name='weight')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('verbose_name', models.CharField(blank=True, max_length=20)),
                ('scale_factor', models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=1e-06, message='Unit scale factor must be positive.')])),
                ('is_base', models.BooleanField(default=False)),
                ('unit_type', models.CharField(choices=[('Ounce', 'OUNCE'), ('Pound', 'POUND'), ('Ton', 'TON'), ('Gram', 'GRAM'), ('Kilogram', 'KILOGRAM'), ('FluidOunce', 'FLUIDOUNCE'), ('Pint', 'PINT'), ('Quart', 'QUART'), ('Gallon', 'GALLON'), ('Milliliter', 'MILLILITER'), ('Metercubed', 'CUBICMETER'), ('MiliGram', 'MILIGRAM'), ('Liter', 'LITER'), ('Dozen', 'DOZEN'), ('Count', 'COUNT'), ('Cartoon', 'CARTOON')], default='count', max_length=10)),
            ],
        ),
    ]
