# Generated by Django 3.0.7 on 2020-09-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='reference_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
