# Generated by Django 3.0.7 on 2020-08-18 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=230)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('de-activated', 'DE ACTIVATED')], default='active', max_length=50)),
                ('customer_number', models.CharField(default=None, max_length=255, null=True)),
                ('is_organization', models.BooleanField(default=False)),
                ('is_individual', models.BooleanField(default=False)),
                ('banking_details', models.TextField(blank=True, default='')),
                ('website', models.CharField(blank=True, max_length=255)),
                ('bp_number', models.CharField(blank=True, max_length=64)),
                ('email', models.CharField(blank=True, max_length=128)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(blank=True, max_length=150)),
                ('street_address', models.CharField(blank=True, default='', max_length=150)),
                ('floor_number', models.CharField(blank=True, default='', max_length=10)),
                ('apartment_number', models.CharField(blank=True, default='', max_length=6)),
                ('city', models.CharField(blank=True, default='', max_length=6)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='customers.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
