export const GET_ACCOUNT_TYPES_CATEGORY_CHOICES = 'GET_ACCOUNT_TYPES_CATEGORY_CHOICES';
export const GET_ACCOUNT_TYPES_CLASSIFICATION_CHOICES = 'GET_ACCOUNT_TYPES_CLASSIFICATION_CHOICES';
export const GET_ASSETS_DEPRECIATION_METHOD_CHOICES = 'GET_ASSETS_DEPRECIATION_METHOD_CHOICES';
export const GET_ASSET_TYPES_CHOICES = 'GET_ASSET_TYPES_CHOICES';
export const GET_ACCOUNT_TYPE_CHOICES = 'GET_ACCOUNT_TYPE_CHOICES';
export const GET_BILL_FREQUENCY_CHOICES = 'GET_BILL_FREQUENCY_CHOICES';
export const GET_ACCOUNT_BALANCE_SHEET_CATEGORIES_CHOICES = 'GET_ACCOUNT_BALANCE_SHEET_CATEGORIES_CHOICES';
export const GET_INTEREST_INTERVAL_ACCOUNT_CHOICES = 'GET_INTEREST_INTERVAL_ACCOUNT_CHOICES';
export const GET_ACCOUNT_INTEREST_METHOD_CHOICES = 'GET_ACCOUNT_INTEREST_METHOD_CHOICES';
export const GET_INVENTORY_VALUATION_PERIOD_CHOICES = 'GET_INVENTORY_VALUATION_PERIOD_CHOICES';
export const GET_INVENTORY_VALUATION_METHODS_CHOICES = 'GET_INVENTORY_VALUATION_METHODS_CHOICES';
export const GET_INVENTORY_CHECK_FREQUENCY_CHOICES = 'GET_INVENTORY_CHECK_FREQUENCY_CHOICES';
export const GET_INVENTORY_CHECK_DATE_CHOICES = 'GET_INVENTORY_CHECK_DATE_CHOICES';
export const GET_UNIT_OF_MEASURE_CHOICES = 'GET_UNIT_OF_MEASURE_CHOICES';
export const GET_CUSTOMER_ADDRESS_TYPE_CHOICES = 'GET_CUSTOMER_ADDRESS_TYPE_CHOICES';
export const GET_EMPLOYEES_ATTENDANCE_STATUS_CHOICES = 'GET_EMPLOYEES_ATTENDANCE_STATUS_CHOICES';
export const GET_EMPLOYEES_TYPE_CHOICES = 'GET_EMPLOYEES_TYPE_CHOICES';
export const GET_BILL_PAYMENT_STATUS_CHOICES = 'GET_BILL_PAYMENT_STATUS_CHOICES';
export const GET_SUPPLIER_ADDRESS_TYPE_CHOICES = 'GET_SUPPLIER_ADDRESS_TYPE_CHOICES';
export const GET_SUPPLIER_STATUS_CHOICES = 'GET_SUPPLIER_STATUS_CHOICES';
export const GET_CUSTOMER_STATUS_CHOICES = 'GET_CUSTOMER_STATUS_CHOICES';
export const GET_BILLING_CHOICES = 'GET_BILLING_CHOICES';
export const GET_BILL_PAYMENT_METHODS_CHOICES = 'GET_BILL_PAYMENT_METHODS_CHOICES';
export const GET_INVOICE_SALES_TYPES_CHOICES = 'GET_INVOICE_SALES_TYPES_CHOICES';
export const GET_INVENTORY_ORDER_PAYMENT_METHODS_CHOICES = 'GET_INVENTORY_ORDER_PAYMENT_METHODS_CHOICES';
export const GET_MANUFACTURING_SHIFT_TIME_CHOICES = 'GET_MANUFACTURING_SHIFT_TIME_CHOICES';
export const GET_EVENT_PRIORITY_CHOICES = 'GET_EVENT_PRIORITY_CHOICES';
export const GET_EVENT_PARTICIPANT_TYPES_CHOICES = 'GET_EVENT_PARTICIPANT_TYPES_CHOICES';
export const GET_EVENT_REMINDER_CHOICES = 'GET_EVENT_REMINDER_CHOICES';
export const GET_EVENT_TIME_CHOICES = 'GET_EVENT_TIME_CHOICES';
export const GET_EVENT_ICON_CHOICES = 'GET_EVENT_ICON_CHOICES';
export const GET_EVENT_REPEAT_CHOICES = 'GET_EVENT_REPEAT_CHOICES';
export const GET_EMPLOYEE_PAYROLL_TAX_CHOICES = 'GET_EMPLOYEE_PAYROLL_TAX_CHOICES';
export const GET_NATURE_OF_EMPLOYMENT_CHOICES = 'GET_NATURE_OF_EMPLOYMENT_CHOICES';
export const GET_EMPLOYEE_YEAR_CHOICES = 'GET_EMPLOYEE_YEAR_CHOICES';
export const GET_EMPLOYEE_TIMESHEET_MONTH_CHOICES = 'GET_EMPLOYEE_TIMESHEET_MONTH_CHOICES';
export const GET_EMPLOYEE_PAYSLIP_STATUS_CHOICES = 'GET_EMPLOYEE_PAYSLIP_STATUS_CHOICES';
export const GET_EMPLOYEE_PAYROLL_DATE_CHOICES = 'GET_EMPLOYEE_PAYROLL_DATE_CHOICES';
export const GET_EMPLOYEE_DEDUCTION_METHODS = 'GET_EMPLOYEE_DEDUCTION_METHODS';
export const GET_EMPLOYEE_PAY_FREQUENCIES = 'GET_EMPLOYEE_PAY_FREQUENCIES';
export const GET_EMPLOYEE_LUNCH_CHOICES = 'GET_EMPLOYEE_LUNCH_CHOICES';
export const GET_EMPLOYEE_LEAVE_STATUS_CHOICES = 'GET_EMPLOYEE_LEAVE_STATUS_CHOICES';
export const GET_EMPLOYEE_LEAVE_CATEGORY_CHOICES = 'GET_EMPLOYEE_LEAVE_CATEGORY_CHOICES';
export const GET_EMPLOYEE_CATEGORY_CHOICES = 'GET_EMPLOYEE_CATEGORY_CHOICES';
export const GET_EMPLOYMENT_CONTRACT_TERMINATION_REASONS = 'GET_EMPLOYMENT_CONTRACT_TERMINATION_REASONS';
export const GET_ACCOUNTING_PERIODS_CHOICES = 'GET_ACCOUNTING_PERIODS_CHOICES';
export const GET_JOURNAL_ENTRY_TYPES_CHOICES = 'GET_JOURNAL_ENTRY_TYPES_CHOICES';
export const GET_EMPLOYEES_GENDER_CHOICES = 'GET_EMPLOYEES_GENDER_CHOICES';
export const GET_INVENTORY_TYPES_CHOICES = 'GET_INVENTORY_TYPES_CHOICES';
export const GET_PRODUCT_COMPONENT_PRICING_CHOICES = 'GET_PRODUCT_COMPONENT_PRICING_CHOICES';
export const GET_EQUIPMENT_COMPONENT_CONDITION_CHOICES = 'GET_EQUIPMENT_COMPONENT_CONDITION_CHOICES';
export const GET_INVENTORY_ORDER_STATUS_CHOICES = 'GET_INVENTORY_ORDER_STATUS_CHOICES';
export const GET_INVOICE_SALES_CHOICES = 'GET_INVOICE_SALES_CHOICES';
export const GET_INVOICE_LINE_CHOICES = 'GET_INVOICE_LINE_CHOICES';
export const GET_MANUFACTURING_PROCESS_CHOICES = 'GET_MANUFACTURING_PROCESS_CHOICES';
export const GET_CUSTOMER_PAYMENT_METHODS_CHOICES = 'GET_CUSTOMER_PAYMENT_METHODS_CHOICES';
export const GET_PROCESS_RATE_UNIT_TIME_CHOICES = 'GET_PROCESS_RATE_UNIT_TIME_CHOICES';
export const GET_MANUFACTURING_PRODUCT_TYPES_CHOICES = 'GET_MANUFACTURING_PRODUCT_TYPES_CHOICES';
export const GET_BILL_OF_MATERIALS_LINE_CHOICES = 'GET_BILL_OF_MATERIALS_LINE_CHOICES';
export const GET_PROCESSED_PRODUCTS_STOCK_STATUS_CHOICES = 'GET_PROCESSED_PRODUCTS_STOCK_STATUS_CHOICES';
export const GET_ENTRIES = 'GET_ENTRIES';
export const GET_ERRORS = 'GET_ERRORS';
export const GET_MESSAGES = 'GET_MESSAGES';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const ADD_PROCESS = 'ADD_PROCESS';
export const GET_PROCESSES = 'GET_PROCESSES';
export const ADD_INVOICE = 'ADD_INVOICE';
export const GET_INVOICES = 'GET_INVOICES';
export const GET_INVENTORY_ITEMS = 'GET_INVENTORY_ITEMS';
export const GET_CASH_DRAWERS = 'GET_CASH_DRAWERS';



export const GET_CASH_DRAWERS_START = 'GET_CASH_DRAWERS_START';
export const GET_CASH_DRAWERS_SUCCESS = 'GET_CASH_DRAWERS_SUCCESS';
export const GET_CASH_DRAWERS_FAIL = 'GET_CASH_DRAWERS_FAIL';
export const GET_CASH_DRAWER_START = 'GET_CASH_DRAWER_START';
export const GET_CASH_DRAWER_SUCCESS = 'GET_CASH_DRAWER_SUCCESS';
export const GET_CASH_DRAWER_FAIL = 'GET_CASH_DRAWER_FAIL'


















