export const GET_ERRORS = 'GET_ERRORS';
export const GET_MESSAGES = 'GET_MESSAGES';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const GET_CASH_DRAWERS_START = 'GET_CASH_DRAWERS_START';
export const GET_CASH_DRAWERS_SUCCESS = 'GET_CASH_DRAWERS_SUCCESS';
export const GET_CASH_DRAWERS_FAIL = 'GET_CASH_DRAWERS_FAIL';
export const GET_CASH_DRAWER_START = 'GET_CASH_DRAWER_START';
export const GET_CASH_DRAWER_SUCCESS = 'GET_CASH_DRAWER_SUCCESS';
export const GET_CASH_DRAWER_FAIL = 'GET_CASH_DRAWER_FAIL';
export const GET_INVENTORY_ITEMS_START = 'GET_INVENTORY_ITEMS_START';
export const GET_INVENTORY_ITEMS_SUCCESS = 'GET_INVENTORY_ITEMS_SUCCESS';
export const GET_INVENTORY_ITEMS_FAIL = 'GET_INVENTORY_ITEMS_FAIL';
export const GET_INVOICES_START = 'GET_INVOICES_START';
export const GET_INVOICES_SUCCESS = 'GET_INVOICES_SUCCESS';
export const GET_INVOICES_FAIL = 'GET_INVOICES_FAIL';
export const CREATE_INVOICE_START = 'CREATE_INVOICE_START';
export const CREATE_INVOICE_SUCCESS = 'CREATE_INVOICE_SUCCESS';
export const CREATE_INVOICE_FAIL = 'CREATE_INVOICE_FAIL';
export const EDIT_INVOICE = 'EDIT_INVOICE';
export const GET_JOURNAL_ENTRIES_START = 'GET_JOURNAL_ENTRIES_START';
export const GET_JOURNAL_ENTRIES_SUCCESS = 'GET_JOURNAL_ENTRIES_SUCCESS';
export const GET_JOURNAL_ENTRIES_FAIL = 'GET_JOURNAL_ENTRIES_FAIL';
export const GET_ACCOUNTING_ADJUSTMENTS_START = 'GET_ACCOUNTING_ADJUSTMENTS_START';
export const GET_ACCOUNTING_ADJUSTMENTS_SUCCESS = 'GET_ACCOUNTING_ADJUSTMENTS_SUCCESS';
export const GET_ACCOUNTING_ADJUSTMENTS_FAIL = 'GET_ACCOUNTING_ADJUSTMENTS_FAIL';
export const GET_RAW_MATERIALS_START = 'GET_RAW_MATERIALS_START';
export const GET_RAW_MATERIALS_SUCCESS = 'GET_RAW_MATERIALS_SUCCESS';
export const GET_RAW_MATERIALS_FAIL = 'GET_RAW_MATERIALS_FAIL';
export const CREATE_RAW_MATERIAL_START = 'CREATE_RAW_MATERIAL_START';
export const CREATE_RAW_MATERIAL_SUCCESS = 'CREATE_RAW_MATERIAL_SUCCESS';
export const CREATE_RAW_MATERIAL_FAIL = 'CREATE_RAW_MATERIAL_FAIL';
export const GET_RAW_MATERIAL_START = 'GET_RAW_MATERIAL_START';
export const GET_RAW_MATERIAL_SUCCESS = 'GET_RAW_MATERIAL_SUCCESS';
export const GET_RAW_MATERIAL_FAIL = 'GET_RAW_MATERIAL_FAIL';
export const EDIT_RAW_MATERIAL = 'EDIT_RAW_MATERIAL';






