# Generated by Django 3.0.7 on 2020-08-18 13:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daily_cash_register', '0001_initial'),
        ('accounts', '0002_auto_20200818_1502'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comments', models.TextField()),
                ('reference_number', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditNoteLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('receipt_number', models.CharField(default=None, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('comment', models.CharField(blank=True, default='', max_length=511, null=True)),
                ('payment_method', models.CharField(max_length=500)),
                ('has_finished', models.BooleanField(db_index=True, default=False)),
                ('has_error', models.BooleanField(db_index=True, default=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=16)),
                ('amount_tendered', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('sale_type', models.CharField(choices=[('credit', 'CREDIT'), ('cash', 'CASH'), ('quotation', 'Quotation')], max_length=16)),
                ('status', models.CharField(choices=[('quotation', 'Quotation'), ('invoice', 'Invoice'), ('canceled', 'Cancelled'), ('refunded', 'Refunded'), ('invoice', 'Invoice'), ('sale', 'Sale or Paid in Full'), ('paid-partially', 'Paid Partially')], max_length=16)),
                ('reference_number', models.CharField(default=None, max_length=255, null=True)),
                ('draft', models.BooleanField(blank=True, default=True)),
                ('due', models.DateField(default=datetime.date.today)),
                ('date', models.DateField(default=datetime.date.today)),
                ('terms', models.CharField(blank=True, max_length=128)),
                ('comments', models.TextField(blank=True)),
                ('archived', models.BooleanField(default=False)),
                ('is_voided', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesGroupPricingDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=230)),
                ('product_name', models.CharField(max_length=230)),
                ('group_discount_rate', models.FloatField()),
                ('reference_number', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_invoice_comments', models.TextField(blank=True)),
                ('default_quotation_comments', models.TextField(blank=True)),
                ('default_credit_note_comments', models.TextField(blank=True)),
                ('default_terms', models.TextField(blank=True)),
                ('include_shipping_address', models.BooleanField(default=False)),
                ('include_tax_in_invoice', models.BooleanField(default=True)),
                ('include_units_in_sales_invoice', models.BooleanField(default=True)),
                ('next_invoice_number', models.IntegerField(default=1)),
                ('next_quotation_number', models.IntegerField(default=1)),
                ('use_sales_invoice', models.BooleanField(default=True)),
                ('use_service_invoice', models.BooleanField(default=True)),
                ('use_bill_invoice', models.BooleanField(default=True)),
                ('use_combined_invoice', models.BooleanField(default=True)),
                ('is_configured', models.BooleanField(default=False)),
                ('sales_tax', models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Tax')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('amount_tendered', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('amount_to_pay', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('date', models.DateField()),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('debit card', 'Debit Card'), ('mobile', 'Mobile-Transfer')], default='transfer', max_length=32)),
                ('reference_number', models.CharField(default=None, max_length=255, null=True)),
                ('comments', models.TextField(default='Thank you for your business')),
                ('cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inpayments', to='daily_cash_register.CashRegister')),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_payments', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.JournalEntry')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.Invoice')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='invoicing.CustomerReceipt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('line_type', models.PositiveSmallIntegerField(choices=[(1, 'product'), (2, 'service')])),
                ('reference_number', models.CharField(default=None, max_length=255, null=True)),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.SalesGroupPricingDiscount')),
                ('invoice', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='invoicing.Invoice')),
            ],
        ),
    ]
