# Generated by Django 3.0.7 on 2020-09-01 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_auto_20200818_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='reference_number',
            new_name='tracking_number',
        ),
    ]
