# Generated by Django 3.0.7 on 2020-09-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_auto_20200902_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='line_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'service'), (1, 'product')]),
        ),
    ]
