# Generated by Django 3.0.7 on 2020-09-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_auto_20200908_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16),
        ),
    ]
