# Generated by Django 3.0.7 on 2020-09-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_auto_20200908_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceline',
            name='line_type',
        ),
    ]
