# Generated by Django 3.0.7 on 2020-09-12 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0004_auto_20200908_2249'),
        ('invoicing', '0006_remove_invoiceline_line_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicelines', to='manufacture.ProcessProduct'),
        ),
    ]
