# Generated by Django 3.0.7 on 2020-09-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_auto_20200913_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreceipt',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='customerreceipt',
            name='amount_tendered',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount_tendered',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount_to_pay',
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
