# Generated by Django 3.0.7 on 2020-09-12 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0009_auto_20200913_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreceipt',
            name='payment_method',
        ),
    ]
