# Generated by Django 3.0.7 on 2020-09-02 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200902_0038'),
        ('manufacture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturedproductincrement',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='manufacturedproductincrement',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='manufacturedproductincrement',
            name='product',
        ),
        migrations.RenameField(
            model_name='historicalprocessedproductsstockreceiptline',
            old_name='line',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='processedproductsstockreceiptline',
            old_name='line',
            new_name='item',
        ),
        migrations.AddField(
            model_name='historicalprocessedproductsstockreceipt',
            name='process',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manufacture.ProductionProcess'),
        ),
        migrations.AddField(
            model_name='historicalprocessedproductsstockreceipt',
            name='ship_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.WareHouse'),
        ),
        migrations.AddField(
            model_name='processedproductsstockreceipt',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outputs', to='manufacture.ProductionProcess'),
        ),
        migrations.AddField(
            model_name='processedproductsstockreceipt',
            name='ship_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.WareHouse'),
        ),
        migrations.DeleteModel(
            name='ManufacturedProductDecrement',
        ),
        migrations.DeleteModel(
            name='ManufacturedProductIncrement',
        ),
    ]
