# Generated by Django 3.0.7 on 2020-09-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0002_auto_20200902_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processmachine',
            name='description',
        ),
    ]
