# Generated by Django 3.0.7 on 2020-10-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0004_auto_20200908_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocessproduct',
            name='unit',
            field=models.CharField(choices=[('Ounce', 'OUNCE'), ('Pound', 'POUND'), ('Ton', 'TON'), ('Gram', 'GRAM'), ('Kilogram', 'KILOGRAM'), ('FluidOunce', 'FLUIDOUNCE'), ('Pint', 'PINT'), ('Quart', 'QUART'), ('Gallon', 'GALLON'), ('Milliliter', 'MILLILITER'), ('Metercubed', 'CUBICMETER'), ('MiliGram', 'MILIGRAM'), ('Liter', 'LITER'), ('Dozen', 'DOZEN'), ('Count', 'COUNT'), ('Cartoon', 'CARTOON')], default='Count', max_length=100),
        ),
        migrations.AlterField(
            model_name='processproduct',
            name='unit',
            field=models.CharField(choices=[('Ounce', 'OUNCE'), ('Pound', 'POUND'), ('Ton', 'TON'), ('Gram', 'GRAM'), ('Kilogram', 'KILOGRAM'), ('FluidOunce', 'FLUIDOUNCE'), ('Pint', 'PINT'), ('Quart', 'QUART'), ('Gallon', 'GALLON'), ('Milliliter', 'MILLILITER'), ('Metercubed', 'CUBICMETER'), ('MiliGram', 'MILIGRAM'), ('Liter', 'LITER'), ('Dozen', 'DOZEN'), ('Count', 'COUNT'), ('Cartoon', 'CARTOON')], default='Count', max_length=100),
        ),
        migrations.AlterField(
            model_name='wastegenerationreport',
            name='unit',
            field=models.CharField(choices=[('Ounce', 'OUNCE'), ('Pound', 'POUND'), ('Ton', 'TON'), ('Gram', 'GRAM'), ('Kilogram', 'KILOGRAM'), ('FluidOunce', 'FLUIDOUNCE'), ('Pint', 'PINT'), ('Quart', 'QUART'), ('Gallon', 'GALLON'), ('Milliliter', 'MILLILITER'), ('Metercubed', 'CUBICMETER'), ('MiliGram', 'MILIGRAM'), ('Liter', 'LITER'), ('Dozen', 'DOZEN'), ('Count', 'COUNT'), ('Cartoon', 'CARTOON')], default='Count', max_length=100),
        ),
    ]
