# Generated by Django 3.0.7 on 2020-09-12 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200906_1315'),
        ('daily_cash_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashregister',
            old_name='is_open',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='cashregister',
            name='system',
        ),
        migrations.AddField(
            model_name='cashregister',
            name='closed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Currency'),
        ),
    ]
